openapi: 3.0.3
info:
    title: PEA - Pure Email Auth
    description: |
        - [Repository](https://github.com/JacobLinCool/pea)
        - [Demo](https://pea.csie.cool)
    contact:
        email: jacob@csie.cool
    license:
        name: MIT
        url: https://github.com/JacobLinCool/pea/blob/main/LICENSE
    version: 0.0.0
servers:
    - url: https://{server}/api
      variables:
          server:
              default: pea.csie.cool
              description: PEA Server
tags:
    - name: dev
      description: Everything about Developers
    - name: app
      description: Everything about Applications
paths:
    /app:
        post:
            tags:
                - app
            summary: Add a new application
            description: Add a new application
            operationId: addApp
            requestBody:
                description: Add a new application
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/App"
                required: true
            responses:
                "200":
                    description: Successful operation
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/App"
                "405":
                    description: Invalid input
components:
    schemas:
        App:
            required:
                - name
                - photoUrls
            type: object
            properties:
                id:
                    type: string
                    example: my-app
                name:
                    type: string
                    example: My App
                description:
                    type: string
                    description: A short description of the application
    securitySchemes:
        api_key:
            type: apiKey
            name: api_key
            in: header
